<?php

namespace App\Exceptions;

use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Illuminate\Validation\ValidationException;
use Symfony\Component\Routing\Exception\RouteNotFoundException;
use Throwable;

class Handler extends ExceptionHandler
{
    /**
     * A list of the exception types that are not reported.
     *
     * @var array
     */
    protected $dontReport = [
        //
    ];

    /**
     * A list of the inputs that are never flashed for validation exceptions.
     *
     * @var array
     */
    protected $dontFlash = [
        'current_password',
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     *
     * @return void
     */
    public function register()
    {
        $this->reportable(function (Throwable $e) {
            //
        });
    }

    /**
     * Funcion para mostrar la respuesta de message en español,
     * esposible cambiar el valor 'message' por cualquier otro.
     */
    protected function invalidJson($request, ValidationException $exception)
    {
        // TODO: Change the autogenerated stub
        return response()->json([
            'message' => __('Los datos proporcionados no son válidos.'),
            'errors' => $exception->errors(),
        ], $exception->status);
    }

    /**
     * Funcion para mostrar el mensaje de error en formato JSON
     * a una ruta desconocida, a cambio de un HTML
     */
    public function render($request, Throwable $e)
    {
        if ($e instanceof ModelNotFoundException){
            return response()->json([
                'res' => false,
                'error' => 'Modelo no encontrado'
            ], 400);
        }

        if ($e instanceof RouteNotFoundException){
            return response()->json([
                'message' => 'no autorizado, token invalido'
            ], 401);
        }

        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }
}
